### PR TITLE
Fixed contact mail issue

### PR DESCRIPTION
**Pull request by silverslott**
Fixed the e-mail contact being none issue as suggested by Phil :-)

### CODE REVIEW

**Comment by ewels** [comment]
Did you check this by the way? I wrote the code off the top of my head in Slack, so might be worth just checking that it doesn't break stuff 👀 😅

**Comment by silverslott** [comment]
> Did you check this by the way? I wrote the code off the top of my head in Slack, so might be worth just checking that it doesn't break stuff 👀 😅

Anand and I have tested it now, it works!

**Comment by ewels** [comment]
Ok great!

**Review by aanil — APPROVED** [review]
👍

**Comment by aanil** [comment]
@ewels Is the contact email mandatory in our multiqc report? If we implement this, the report will be generated with no contact email, if I'm not wrong.

**Comment by ewels** [comment]
I'm not really sure why it wouldn't be set? This change just stops MultiQC from crashing if that is the case. But yes it would be better to figure out why it's not being set in the long run.

**Pull request merged**
